### ISSUE TITLE
Feature request: Support stock transactions

### ISSUE THREAD

**Issue by SanMiggel** [alex-kn/comdirect-api-simple#3]
Hi Alex,

first of all great project and thanks for your effort! 
I am planning to use it to monitor my stocks, but would need support for some more API functions, especially transactions.
I would be very happy to contribute and add the functionality myselft.

Question: Are you interested in extending this codebase? In that case, I would work on top of this repository and send you a few pull requests. If not, I would work on my own fork.

Best
Michael

**Comment by alex-kn** [comment]
Hi Michael, 

Thank you for your interest in this project. Yes, I am still interested in extending this project.

I would be more than happy to review any pull requests you are sending my way, your effort would be greatly appreciated!
